apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubelet-rubber-stamp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kubelet-rubber-stamp
  template:
    metadata:
      labels:
        name: kubelet-rubber-stamp
    spec:
      serviceAccountName: kubelet-rubber-stamp
      tolerations:
      - effect: NoSchedule
        operator: Exists
      nodeSelector:
        node-role.kubernetes.io/master: ""
      priorityClassName: system-cluster-critical
      containers:
      - name: kubelet-rubber-stamp
        image: {{ .Values.image | default (printf "quay.io/kontena/kubelet-rubber-stamp-amd64:%s" .Chart.AppVersion) }}
        args:
        - "--v=2"
        imagePullPolicy: IfNotPresent
        env:
        - name: WATCH_NAMESPACE
          value: ""
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "kubelet-rubber-stamp"
        resources:
          requests:
            memory: 10Mi
