apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kubelet-rubber-stamp
rules:
- apiGroups:
  - certificates.k8s.io
  resources:
  - signers
  # legacy-unknown: support before kubernetes-1.18.0
  resourceNames:
  - "kubernetes.io/legacy-unknown"
  - "kubernetes.io/kubelet-serving"
  verbs:
  - approve
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests/approval
  verbs:
  - create
  - update
- apiGroups:
  - certificates.k8s.io
  resources:
  - signers
  resourceNames:
  - kubernetes.io/legacy-unknown
  - kubernetes.io/kubelet-serving
  verbs:
  - approve
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - use
  resourceNames:
  - kubelet-rubber-stamp
